import React from "react";
import { useNavigate } from "react-router-dom";
import Navbar from "../Navbar/Navbar";
import Footer from "../Footer/Footer";
import "./TermsOfService.css";

const SECTIONS = [
  {
    id: "acceptance",
    num: "01",
    title: "Acceptance of Terms",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/>
      </svg>
    ),
    content: (
      <>
        <p>By accessing or using SummarizeAI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
        <p>These Terms apply to all users of the Service, including visitors, registered users, and others who access or use the Service. We reserve the right to update or change these Terms at any time, and such changes will be effective immediately upon posting.</p>
        <div className="legal-highlight-box">
          By continuing to use SummarizeAI after changes are posted, you accept and agree to the revised Terms of Service.
        </div>
      </>
    ),
  },
  {
    id: "description",
    num: "02",
    title: "Description of Service",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/>
      </svg>
    ),
    content: (
      <>
        <p>SummarizeAI is an AI-powered email summarization platform that connects to your Gmail account via Google OAuth to fetch, analyze, and summarize your emails. The Service provides:</p>
        <ul>
          <li>Daily and weekly email summaries generated by AI</li>
          <li>Automatic extraction of action items and tasks from your emails</li>
          <li>Priority classification for important messages</li>
          <li>A summary history archive for past digests</li>
          <li>A task management interface for AI-extracted action items</li>
        </ul>
        <p>The Service is intended for personal productivity use. We do not guarantee uninterrupted availability or that the Service will be free of errors at all times.</p>
      </>
    ),
  },
  {
    id: "account",
    num: "03",
    title: "Account & Authentication",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/>
      </svg>
    ),
    content: (
      <>
        <p>Access to SummarizeAI requires authentication through your Google account using OAuth 2.0. By connecting your Google account, you authorize us to access your Gmail data solely for the purposes described in this agreement.</p>
        <ul>
          <li>You are responsible for maintaining the security of your Google account credentials</li>
          <li>You must notify us immediately of any unauthorized use of your account</li>
          <li>We are not liable for any loss resulting from unauthorized use of your account</li>
          <li>You may revoke access at any time via your Google account security settings</li>
        </ul>
        <p>Each account is for a single user only. Sharing accounts or credentials with other individuals is not permitted.</p>
      </>
    ),
  },
  {
    id: "gmail-access",
    num: "04",
    title: "Gmail Data Access",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/>
      </svg>
    ),
    content: (
      <>
        <p>SummarizeAI reads your Gmail messages only to generate summaries and extract tasks on your behalf. We access only what is necessary:</p>
        <ul>
          <li>Email subject lines and body content for summarization</li>
          <li>Sender information to identify important contacts</li>
          <li>Email timestamps for date-range filtering</li>
        </ul>
        <div className="legal-highlight-box">
          We do not send emails on your behalf, delete or modify your emails, share your email content with third parties, or use your email data to train AI models.
        </div>
        <p>Our access to Gmail data is governed by Google's API Services User Data Policy in addition to these Terms. Email content processed by our AI is not stored permanently — only the generated summary is retained.</p>
      </>
    ),
  },
  {
    id: "acceptable-use",
    num: "05",
    title: "Acceptable Use",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
      </svg>
    ),
    content: (
      <>
        <p>You agree not to use SummarizeAI for any unlawful purpose or in any way that could damage, disable, or impair the Service. Prohibited activities include:</p>
        <ul>
          <li>Attempting to gain unauthorized access to our systems or other users' accounts</li>
          <li>Using automated scripts or bots to interact with the Service beyond normal usage</li>
          <li>Reverse engineering, decompiling, or disassembling any part of the Service</li>
          <li>Reselling or commercially exploiting the Service without prior written consent</li>
          <li>Uploading or transmitting malicious code or viruses</li>
          <li>Violating any applicable local, national, or international law or regulation</li>
        </ul>
        <p>Violation of these terms may result in immediate termination of your access without notice.</p>
      </>
    ),
  },
  {
    id: "intellectual-property",
    num: "06",
    title: "Intellectual Property",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 015.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/>
      </svg>
    ),
    content: (
      <>
        <p>All content, features, and functionality of SummarizeAI — including but not limited to the software, design, text, graphics, and AI-generated summaries — are owned by SummarizeAI and are protected by intellectual property laws.</p>
        <p>You retain full ownership of your email data. By using the Service, you grant us a limited, non-exclusive license to process your email content solely for the purpose of generating summaries for you.</p>
        <p>AI-generated summaries produced for your account are for your personal use only and may not be redistributed commercially without permission.</p>
      </>
    ),
  },
  {
    id: "disclaimers",
    num: "07",
    title: "Disclaimers & Limitations",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
      </svg>
    ),
    content: (
      <>
        <p>The Service is provided on an "as is" and "as available" basis without warranties of any kind, either express or implied. We do not warrant that:</p>
        <ul>
          <li>AI-generated summaries will be accurate, complete, or error-free</li>
          <li>The Service will be uninterrupted, timely, or secure</li>
          <li>Results obtained from using the Service will meet your requirements</li>
        </ul>
        <p>To the fullest extent permitted by law, SummarizeAI shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of or inability to use the Service.</p>
        <div className="legal-highlight-box">
          AI summaries are for informational purposes only. Always refer to your original emails for critical decisions.
        </div>
      </>
    ),
  },
  {
    id: "termination",
    num: "08",
    title: "Termination",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/>
      </svg>
    ),
    content: (
      <>
        <p>You may stop using the Service at any time by revoking Gmail access from your Google Account settings and ceasing to use the platform. Upon revocation, we will not fetch any further data from your account.</p>
        <p>We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.</p>
        <p>Upon termination, your right to use the Service will immediately cease, and we may delete your stored summaries and account data in accordance with our data retention policy.</p>
      </>
    ),
  },
  {
    id: "contact",
    num: "09",
    title: "Contact Us",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/>
      </svg>
    ),
    content: (
      <>
        <p>If you have any questions about these Terms of Service, please contact us:</p>
        <div className="legal-contact-grid">
          <div className="legal-contact-card">
            <div className="legal-contact-card-label">Email</div>
            <div className="legal-contact-card-value">esummerizer@gmail.com</div>
          </div>
          <div className="legal-contact-card">
            <div className="legal-contact-card-label">Response Time</div>
            <div className="legal-contact-card-value">Within 2 business days</div>
          </div>
        </div>
      </>
    ),
  },
];

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="legal-root">
      <Navbar />

      {/* Hero */}
      <div className="legal-hero" style={{ marginTop: "4rem" }}>
        <div className="legal-hero-badge">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
          </svg>
          Legal
        </div>
        <h1 className="legal-hero-title">Terms of Service</h1>
        <br />
        <p className="legal-hero-sub">
          Please read these terms carefully before using SummarizeAI. They govern your use of our email summarization platform.
        </p>
        <div className="legal-meta-row">
          <span className="legal-meta-pill">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/>
            </svg>
            Effective: May 30, 2026
          </span>
          <span className="legal-meta-pill">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>
            </svg>
            ~5 min read
          </span>
          <span className="legal-meta-pill">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/>
            </svg>
            Version 1.1
          </span>
        </div>
      </div>

      {/* Layout */}
      <div className="legal-layout">
        {/* TOC */}
        <aside className="legal-toc">
          <div className="legal-toc-inner">
            <div className="legal-toc-title">Contents</div>
            <ul className="legal-toc-list">
              {SECTIONS.map((s) => (
                <li key={s.id}>
                  <a href={`#${s.id}`}>{s.num}. {s.title}</a>
                </li>
              ))}
            </ul>
          </div>
        </aside>

        {/* Content */}
        <main className="legal-content">
          <button className="legal-back-btn" onClick={() => navigate(-1)}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/>
            </svg>
            Back
          </button>

          {SECTIONS.map((s) => (
            <section className="legal-section" id={s.id} key={s.id}>
              <div className="legal-section-header">
                <div className="legal-section-icon">{s.icon}</div>
                <div>
                  <div className="legal-section-num">Section {s.num}</div>
                  <h2 className="legal-section-title">{s.title}</h2>
                </div>
              </div>
              {s.content}
            </section>
          ))}
        </main>
      </div>

      <Footer />
    </div>
  );
}